### PR TITLE
Try-fix traceroute panic

### LINKED ISSUE #8565: [Bug]: t-lora pager core panic
### Category

Other

### Hardware

Other

### Is this bug report about any UI component firmware like InkHUD or Meshtatic UI (MUI)?

- [ ] Meshtastic UI aka MUI colorTFT
- [ ] InkHUD ePaper
- [x] OLED slide UI on any display

### Firmware Version

2.7.13

### Description

All my 2.7 for t-lora pager experienced it.
Mostly while some work with trace for example, it just reboots.
Also i see no watch had got time from lora while t-deck doing it easily.

[13:07:52]DEBUG | ??:??Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1).

### Relevant log output

```Shell
[13:07:22]INFO  | ??:??:?? 671 [Router] Route traced:
[13:07:22]0x9eecb2c4 --> 0xb2a72678 (0.00dB) --> 0x9ea13f34 (-19.25dB) --> 0x6982b394 (0.00dB) --> 0xdb5177e8 (-17.25dB) --> 0x433bf034 (3.50dB) --> 0xb3b
[13:07:22]DEBUG | ??:??:?? 671 [Router] Module 'traceroute' considered
[13:07:22]DEBUG | ??:??:?? 671 [Router] Module 'routing' wantsPacket=1
[13:07:22]INFO  | ??:??:?? 671 [Router] Received routing from=0xb3b2420b, id=0x231f5ad, portnum=70, payloadlen=127
[13:07:22]DEBUG | ??:??:?? 671 [Router] Routing sniffing (id=0x0231f5ad fr=0xb3b2420b to=0x9eecb2c4, transport = 1, WantAck=1, HopLim=0 Ch=0x0 Portnum=70 requestId=1caafd05 rxSNR=5.5 rxRSSI=-87 hopS
[13:07:22]DEBUG | ??:??:?? 671 [Router] cancelSending id=0x1caafd05, removed=0
[13:07:22]DEBUG | ??:??:?? 671 [Router] Module 'routing' considered
[13:07:27]DEBUG | ??:??:?? 676 Rotary event CW
[13:07:27]DEBUG | ??:??:?? 676 State: ON
[13:07:27]INFO  | ??:??:?? 676 Input event 28! kb 0
[13:07:27]INFO  | ??:??:?? 676 [Screen] Turn on screen
[13:07:28]DEBUG | ??:??:?? 676 Rotary event CW
[13:07:28]INFO  | ??:??:?? 676 Input event 28! kb 0
[13:07:28]G | ??:??:?? 677 Rory event CW
[13:07:28]INFO  | ??:??:?? 677 Input event 28! kb 0
[13:07:28]DEBUG | ??:??:?? 677 Rotary event CW
[13:07:28]INFO  | ??:??:?? 677 Input event 28! kb 0
[13:07:29]DEBUG|?:??:?78 34mRot eventC
[13:07:29]INFO  | ??:??:?? 678 Input event 28! kb 0
[13:07:29]DEBUG | ??:??:?? 678 [Screen] Rotary event CW
[13:07:29]INFO  | ??:??:?? 678 Input event 28! kb 0
[13:07:30]EBUG | ??:??:?Rotay event CW
[13:07:30]INFO  | ??:??:?? 679 Input event 28! kb 0
[13:07:30]DEBUG | ??:??:?? 679 Rotary event CW
[13:07:30]INFO  | ??:??:?? 679 Input event 28! kb 0
[13:07:31]DEBUG | ??:??:?? 679 Rotary event CW
[13:07:31]INFO  | ??:??:?? 680 Input event 28! kb 0
[13:07:31]DEBUG | ??:??:?? 680 Rotary event Press
[13:07:31]DEBUG | ??:??:?? 680 Rotary event Press
[13:07:31]INFO  | ??:??:?? 680 Input event 10! kb 0
[13:07:31]INFO  | ??:??:?? 680 Input event 10! kb 0
[13:07:34]??:??:?? 683 Rotary event Press
[13:07:34]INFO  | ??:??:?? 683 Input event 10! kb 0
[13:07:35]DE| ?:??:?? 684 [34motary event CC
[13:07:35]INFO  | ??:??:?? 684 Input event 29! kb 0
[13:07:35]DEBUG | ??:??:?? 684 [RadioIf] Corrected frequency offset: 531.843689
[13:07:35]DEBUG | ??:??:?? 684 [RadioIf] Lora RX (id=0xfa38aed4 fr=0xf329bab0 to=0xffffffff, transport = 0, WantAck=0, HopLim=2 Ch=0x8 encrypted len=95 rxSNR=6.25 rxRSSI=-83 hopStart=5 relay=0x78)
[13:07:35]DEBUG | ??:??:?? 684 [RadioIf] Packet RX: 968ms
[13:07:35]INFO  | ??:??:?? 684 [Router] Packet History - insert: Using new slot @uptime 684.321s TRACE NEW
[13:07:35]DEBUG | ??:??:?? 684 [Router] Use channel 0 (hash 0x8)
[13:07:35]DEBUG | ??:??:?? 684 [Router] Expand short PSK #1
[13:07:35]DEBUG | ??:??:?? 684 [Router] Use AES128 key!
[13:07:35]DEBUG | ??:??:?? 684 [Router] decoded message (id=0xfa38aed4 fr=0xf329bab0 to=0xffffffff, transport = 1, WantAck=0, HopLim=2 Ch=0x0 Portnum=4 rxSNR=6.25 rxRSSI=-83 hopStart=5 relay=0x78)
[13:07:35]DEBUG | ??:??:?? 684 [Router] handleReceived(REMOTE) (id=0xfa38aed4 fr=0xf329bab0 to=0xffffffff, transport = 1, WantAck=0, HopLim=2 Ch=0x0 Portnum=4 rxSNR=6.25 rxRSSI=-83 hopStart=5 relay=
[13:07:35]DEBUG | ??:??:?? 684 [Router] Module 'nodeinfo' wantsPacket=1
[13:07:35]INFO  | ??:??:?? 684 [Router] Received nodeinfo from=0xf329bab0, id=0xfa38aed4, portnum=4, payloadlen=73
[13:07:35]INFO  | ??:??:?? 684 [Router] Adding node to database with 17 nodes and 118484 bytes free!
[13:07:35]DEBUG | ??:??:?? 684 [Router] Incoming Pubkey:  e5 b6 d0 16 5b 94 5d 86 dc 35 6a ec 67 bb 68 2c a3 c6 73 58 7f 15 d3 e3 cd 62 53 74 cf ae 0e 25
[13:07:35]
[13:07:35]INFO  | ??:??:?? 684 [Router] Update Node Pubkey!
[13:07:35]DEBUG | ??:??:?? 684 [Router] Saved Pubkey:  e5 b6 d0 16 5b 94 5d 86 dc 35 6a ec 67 bb 68 2c a3 c6 73 58 7f 15 d3 e3 cd 62 53 74 cf ae 0e 25
[13:07:35]
[13:07:35]DEBUG | ??:??:?? 684 [Router] Update changed=1 user Strl_114/St14, id=0xf329bab0, channel=0
[13:07:35]DEBUG | ??:??:?? 684 [Router] Node status update: 17 online, 17 total
[13:07:35]DEBUG | ??:??:?? 684 [Router] Show standard frames
[13:07:35]DEBUG | ??:??:?? 684 [Router] Show 8 module frames
[13:07:35]DEBUG | ??:??:?? 684 [Router] Added modules.  numframes: 8
[13:07:35]DEBUG | ??:??:?? 684 [Router] Finished build frames. numframes: 9
[13:07:35]DEBUG | ??:??:?? 684 [Router] Save to disk 16
[13:07:35]DEBUG | ??:??:?? 684 [Router] Opening /prefs/nodes.proto, fullAtomic=0
[13:07:35]INFO  | ??:??:?? 684 [Router] Save /prefs/nodes.proto
[13:07:35]DEBUG | ??:??:?? 684 [Router] Module 'nodeinfo' considered
[13:07:35]DEBUG | ??:??:?? 684 [Router] Module 'routing' wantsPacket=1
[13:07:35]INFO  | ??:??:?? 684 [Router] Received routing from=0xf329bab0, id=0xfa38aed4, portnum=4, payloadlen=73
[13:07:35]DEBUG | ??:??:?? 684 [Router] Routing sniffing (id=0xfa38aed4 fr=0xf329bab0 to=0xffffffff, transport = 1, WantAck=0, HopLim=2 Ch=0x0 Portnum=4 rxSNR=6.25 rxRSSI=-83 hopStart=5 relay=0x78)
[13:07:35]DEBUG | ??:??:?? 684 [Router] No rebroadcast: Role = CLIENT_MUTE or Rebroadcast Mode = NONE
[13:07:35]DEBUG | ??:??:?? 684 [Router] Delivering rx packet (id=0xfa38aed4 fr=0xf329bab0 to=0xffffffff, transport = 1, WantAck=0, HopLim=2 Ch=0x0 Portnum=4 rxSNR=6.25 rxRSSI=-83 hopStart=5 relay=0x
[13:07:35]DEBUG | ??:??:?? 684 [Router] Update DB node 0xf329bab0, rx_time=0
[13:07:35]INFO  | ??:??:?? 684 [Router] Sort took 0 milliseconds
[13:07:35]DEBUG | ??:??:?? 684 [Router] Forwarding to phone (id=0xfa38aed4 fr=0xf329bab0 to=0xffffffff, transport = 1, WantAck=0, HopLim=2 Ch=0x0 Portnum=4 rxSNR=6.25 rxRSSI=-83 hopStart=5 relay=0x7
[13:07:35]DEBUG | ??:??:?? 684 [Router] Module 'routing' considered
[13:07:36]DEBUG | ??:??:?? 685 Rotary event CCW
[13:07:36]INFO  | ??:??:?? 685 Input event 29! kb 0
[13:07:37]ERROR | ??:??:?? 686 [RadioIf] Ignore received packet due to error=-7 (maybe to=0xffffffff, from=0xf329bab0, flags=0xa1)
[13:07:37]DEBUG | ??:??:?? 686 [RadioIf] Packet RX (noise?) : 968ms
[13:07:37]DEBUG | ??:??:?? 686 Rotary event CW
[13:07:37]INFO  | ??:??:?? 686 Input event 28! kb 0
[13:07:37]UG | ??:?:?? 686Rotaev C0mINFO  | ??:??:?? 686 Input event 29! kb 0
[13:07:39]DEBUG | ??:??:?? 687 Rotary event Press
[13:07:39]INFO  | ??:??:?? 688 Input event 10! kb 0
[13:07:39]DEBUG | ??:??:?? 688 Show standard frames
[13:07:39]INFO  | ??:??:?? 688 TraceRoute shouldDraw: runState=1, draw=1
[13:07:39]DEBUG | ??:??:?? 688 traceroute wants a UI Frame
[13:07:39]DEBUG | ??:??:?? 688 Show 9 module frames
[13:07:39]DEBUG | ??:??:?? 688 Added modules.  numframes: 9
[13:07:39]DEBUG | ??:??:?? 688 Finished build frames. numframes: 10
[13:07:39]INFO  | ??:??:?? 688 Creating RouteDiscovery protobuf...
[13:07:39]DEBUG | ??:??:?? 688 Partially randomized packet id 754628742
[13:07:39]INFO  | ??:??:?? 688 Packet allocated successfully: to=0xb2a72678, portnum=70, want_response=1, payload_size=0
[13:07:39]DEBUG | ??:??:?? 688 Ignore update from self
[13:07:39]DEBUG | ??:??:?? 688 localSend to channel 0
[13:07:39]DEBUG | ??:??:?? 688 Setting next retransmission in 6858 msecs: 
[13:07:39]DEBUG | ??:??:?? 688  (id=0x2cfab886 fr=0x7d085940 to=0xb2a72678, transport = 0, WantAck=1, HopLim=5 Ch=0x0 Portnum=70 WANTRESP)
[13:07:39]INFO  | ??:??:?? 688 Packet History - insert: Using new slot @uptime 688.103s TRACE NEW
[13:07:39]DEBUG | ??:??:?? 688 Setting next hop for packet with dest b2a72678 to 78
[13:07:39]DEBUG | ??:??:?? 688 Expand short PSK #1
[13:07:39]DEBUG | ??:??:?? 688 Use AES128 key!
[13:07:39]DEBUG | ??:??:?? 688 enqueue for send (id=0x2cfab886 fr=0x7d085940 to=0xb2a72678, transport = 0, WantAck=1, HopLim=5 Ch=0x8 encrypted len=22 hopStart=5 nextHop=0x78 relay=0x40 pri
[13:07:39]DEBUG | ??:??:?? 688 txGood=5,txRelay=0,rxGood=25,rxBad=3
[13:07:39]INFO  | ??:??:?? 688 tophone queue status queue is full, discard oldest
[13:07:39]INFO  | ??:??:?? 688 sendToMesh called successfully for trace route to node 0xb2a72678
[13:07:39]DEBUG | ??:??:?? 688 [Screen] TraceRoute drawFrame called: runState=1
[13:07:39]DEBUG | ??:??:?? 688 [RadioIf] Started Tx (id=0x2cfab886 fr=0x7d085940 to=0xb2a72678, transport = 0, WantAck=1, HopLim=5 Ch=0x8 encrypted len=22 hopStart=5 nextHop=0x78 relay=0x40 priority=
[13:07:39]DEBUG | ??:??:?? 688 [RadioIf] 0 packets remain in the TX queue
[13:07:39]DEBUG | ??:??:?? 688 [RadioIf] Packet TX: 395ms
[13:07:39]DEBUG | ??:??:?? 688 [RadioIf] Completed sending (id=0x2cfab886 fr=0x7d085940 to=0xb2a72678, transport = 0, WantAck=1, HopLim=5 Ch=0x8 encrypted len=22 hopStart=5 nextHop=0x78 relay=0x40 pr
[13:07:40]DEBUG | ??:??:?? 689 [Screen] TraceRoute drawFrame called: runState=1
[13:07:41]DEBUG | ??:??:?? 690 [Screen] TraceRoute drawFrame called: runState=1
[13:07:42]DEBUG | ??:??:?? 691 [Screen] TraceRoute drawFrame called: runState=1
[13:07:42]DEBUG | ??:??:?? 691 [Power] BQ27220 time to full charge: 0 min
[13:07:42]DEBUG | ??:??:?? 691 [Power] Battery: usbPower=1, isCharging=1, batMv=4274, batPct=100
[13:07:42]DEBUG | ??:??:?? 691 [Screen] TraceRoute drawFrame called: runState=1
[13:07:43]DEBUG | ??:??:?? 692 [Screen] TraceRoute drawFrame called: runState=1
[13:07:44]DEBUG | ??:??:?? 693 [Screen] TraceRoute drawFrame called: runState=1
[13:07:45]DEBUG | ??:??:?? 694 [Screen] TraceRoute drawFrame called: runState=1
[13:07:46]DEBUG | ??:??:?? 694 [Router] Sending retransmission fr=0x7d085940,to=0xb2a72678,id=0x2cfab886, tries left=2
[13:07:46]INFO  | ??:??:?? 694 [Router] Packet History - insert: Reusing slot aged 6.851s TRACE MATCHED PACKET
[13:07:46]DEBUG | ??:??:?? 694 [Router] Setting next hop for packet with dest b2a72678 to 78
[13:07:46]DEBUG | ??:??:?? 694 [Router] Expand short PSK #1
[13:07:46]DEBUG | ??:??:?? 694 [Router] Use AES128 key!
[13:07:46]DEBUG | ??:??:?? 694 [Router] enqueue for send (id=0x2cfab886 fr=0x7d085940 to=0xb2a72678, transport = 0, WantAck=1, HopLim=5 Ch=0x8 encrypted len=22 hopStart=5 nextHop=0x78 relay=0x40 pri
[13:07:46]DEBUG | ??:??:?? 694 [Router] txGood=6,txRelay=0,rxGood=25,rxBad=3
[13:07:46]DEBUG | ??:??:?? 694 [Router] Setting next retransmission in 6858 msecs: 
[13:07:46]DEBUG | ??:??:?? 695 [Router]  (id=0x2cfab886 fr=0x7d085940 to=0xb2a72678, transport = 0, WantAck=1, HopLim=5 Ch=0x0 Portnum=70 WANTRESP)
[13:07:46]DEBUG | ??:??:?? 695 [RadioIf] Started Tx (id=0x2cfab886 fr=0x7d085940 to=0xb2a72678, transport = 0, WantAck=1, HopLim=5 Ch=0x8 encrypted len=22 hopStart=5 nextHop=0x78 relay=0x40 priority=
[13:07:46]DEBUG | ??:??:?? 695 [RadioIf] 0 packets remain in the TX queue
[13:07:46]DEBUG | ??:??:?? 695 [RadioIf] Packet TX: 395ms
[13:07:46]DEBUG | ??:??:?? 695 [RadioIf] Completed sending (id=0x2cfab886 fr=0x7d085940 to=0xb2a72678, transport = 0, WantAck=1, HopLim=5 Ch=0x8 encrypted len=22 hopStart=5 nextHop=0x78 relay=0x40 pr
[13:07:46]DEBUG | ??:??:?? 695 [Screen] TraceRoute drawFrame called: runState=1
[13:07:47]DEBUG | ??:??:?? 696 [Screen] TraceRoute drawFrame called: runState=1
[13:07:47]DEBUG | ??:??:?? 696 [RadioIf] Corrected frequency offset: 549.281250
[13:07:47]DEBUG | ??:??:?? 696 [RadioIf] Lora RX (id=0x92bacd1e fr=0xb2a72678 to=0x7d085940, transport = 0, WantAck=1, HopLim=2 Ch=0x8 encrypted len=30 rxSNR=6.25 rxRSSI=-73 hopStart=2 nextHop=0x40 r
[13:07:47]DEBUG | ??:??:?? 696 [RadioIf] Packet RX: 477ms
[13:07:47]INFO  | ??:??:?? 696 [Router] Packet History - insert: Using new slot @uptime 696.782s TRACE NEW
[13:07:47]DEBUG | ??:??:?? 696 [Router] Use channel 0 (hash 0x8)
[13:07:47]DEBUG | ??:??:?? 696 [Router] Expand short PSK #1
[13:07:47]DEBUG | ??:??:?? 696 [Router] Use AES128 key!
[13:07:47]DEBUG | ??:??:?? 696 [Router] decoded message (id=0x92bacd1e fr=0xb2a72678 to=0x7d085940, transport = 1, WantAck=1, HopLim=2 Ch=0x0 Portnum=70 requestId=2cfab886 rxSNR=6.25 rxRSSI=-73 hopS
[13:07:47]DEBUG | ??:??:?? 696 [Router] handleReceived(REMOTE) (id=0x92bacd1e fr=0xb2a72678 to=0x7d085940, transport = 1, WantAck=1, HopLim=2 Ch=0x0 Portnum=70 requestId=2cfab886 rxSNR=6.25 rxRSSI=-
[13:07:47]DEBUG | ??:??:?? 696 [Router] Module 'traceroute' wantsPacket=1
[13:07:47]INFO  | ??:??:?? 696 [Router] Received traceroute from=0xb2a72678, id=0x92bacd1e, portnum=70, payloadlen=3
[13:07:47]INFO  | ??:??:?? 696 [Router] Route traced:
[13:07:47]0x7d085940 --> 0xb2a72678 (7.00dB)
[13:07:47](6.25dB) 0x7d085940 <-- 0xb2a72678
[13:07:47]INFO  | ??:??:?? 696 [Router] TracRoute packet analysis: tracingNode=0xb2a72678, p.from=0xb2a72678, p.to=0x7d085940, request_id=0x2cfab886
[13:07:47]INFO  | ??:??:?? 696 [Router] TracRoute conditions: isResponseFromTarget=1, isRequestToUs=0, containsTargetNode=0, hasCompleteRoute=0
[13:07:47]INFO  | ??:??:?? 696 [Router] TracRoute result detected: isResponseFromTarget=1, isRequestToUs=0
[13:07:47]INFO  | ??:??:?? 696 [Router] SNR arrays - towards_count=1, back_count=1
[13:07:47]INFO  | ??:??:?? 696 [Router] SNR towards[0] = 28 (7.0dB)
[13:07:47]INFO  | ??:??:?? 696 [Router] SNR back[0] = 25 (6.2dB)
[13:07:47]INFO  | ??:??:?? 696 [Router] Trace route result: Zed8 > Zed9(7.0dB)
[13:07:47]Zed9 > Zed8(6.2dB)
[13:07:47]INFO  | ??:??:?? 696 [Router] TraceRoute result ready, requesting focus. Result: Zed8 > Zed9(7.0dB)
[13:07:47]Zed9 > Zed8(6.2dB)
[13:07:47]DEBUG | ??:??:?? 696 [Router] Show standard frames
[13:07:47]INFO  | ??:??:?? 696 [Router] TraceRoute shouldDraw: runState=2, draw=1
[13:07:47]DEBUG | ??:??:?? 696 [Router] traceroute wants a UI Frame
[13:07:47]DEBUG | ??:??:?? 696 [Router] Show 9 module frames
[13:07:47]DEBUG | ??:??:?? 696 [Router] Added modules.  numframes: 9
[13:07:48]DEBUG | ??:??:?? 696 [Router] Finished build frames. numframes: 10
[13:07:48]INFO  | ??:??:?? 696 [Router] === TraceRoute handleTraceRouteResult END ===
[13:07:48]DEBUG | ??:??:?? 696 [Router] Module 'traceroute' considered
[13:07:48]DEBUG | ??:??:?? 696 [Router] Module 'routing' wantsPacket=1
[13:07:48]INFO  | ??:??:?? 696 [Router] Received routing from=0xb2a72678, id=0x92bacd1e, portnum=70, payloadlen=6
[13:07:48]DEBUG | ??:??:?? 696 [Router] Routing sniffing (id=0x92bacd1e fr=0xb2a72678 to=0x7d085940, transport = 1, WantAck=1, HopLim=2 Ch=0x0 Portnum=70 requestId=2cfab886 rxSNR=6.25 rxRSSI=-73 hop
[13:07:48]DEBUG | ??:??:?? 696 [Router] Partially randomized packet id 43928711
[13:07:48]DEBUG | ??:??:?? 696 [Router] localSend to channel 0
[13:07:48]INFO  | ??:??:?? 696 [Router] Packet History - insert: Using new slot @uptime 696.982s TRACE NEW
[13:07:48]DEBUG | ??:??:?? 696 [Router] Setting next hop for packet with dest b2a72678 to 78
[13:07:48]DEBUG | ??:??:?? 696 [Router] Expand short PSK #1
[13:07:48]DEBUG | ??:??:?? 697 [Router] Use AES128 key!
[13:07:48]DEBUG | ??:??:?? 697 [Router] enqueue for send (id=0x029e4c87 fr=0x7d085940 to=0xb2a72678, transport = 0, WantAck=0, HopLim=0 Ch=0x8 encrypted len=29 nextHop=0x78 relay=0x40 priority=120)
[13:07:48]DEBUG | ??:??:?? 697 [Router] txGood=7,txRelay=0,rxGood=26,rxBad=3
[13:07:48]DEBUG | ??:??:?? 697 [Router] Received a ACK for 0x2cfab886, stopping retransmissions
[13:07:48]DEBUG | ??:??:?? 697 [Router] cancelSending id=0x2cfab886, removed=0
[13:07:48]DEBUG | ??:??:?? 697 [Router] Delivering rx packet (id=0x92bacd1e fr=0xb2a72678 to=0x7d085940, transport = 1, WantAck=1, HopLim=2 Ch=0x0 Portnum=70 requestId=2cfab886 rxSNR=6.25 rxRSSI=-73
[13:07:48]DEBUG | ??:??:?? 697 [Router] Update DB node 0xb2a72678, rx_time=0
[13:07:48]INFO  | ??:??:?? 697 [Router] Sort took 0 milliseconds
[13:07:48]DEBUG | ??:??:?? 697 [Router] Forwarding to phone (id=0x92bacd1e fr=0xb2a72678 to=0x7d085940, transport = 1, WantAck=1, HopLim=2 Ch=0x0 Portnum=70 requestId=2cfab886 rxSNR=6.25 rxRSSI=-73 
[13:07:48]DEBUG | ??:??:?? 697 [Router] Module 'routing' considered
[13:07:48]DEBUG | ??:??:?? 697 [Screen] TraceRoute drawFrame called: runState=2
[13:07:48]DEBUG | ??:??:?? 697 [RadioIf] Started Tx (id=0x029e4c87 fr=0x7d085940 to=0xb2a72678, transport = 0, WantAck=0, HopLim=0 Ch=0x8 encrypted len=29 nextHop=0x78 relay=0x40 priority=120)
[13:07:48]DEBUG | ??:??:?? 697 [RadioIf] 0 packets remain in the TX queue
[13:07:48]DEBUG | ??:??:?? 697 [RadioIf] Packet TX: 477ms
[13:07:48]DEBUG | ??:??:?? 697 [RadioIf] Completed sending (id=0x029e4c87 fr=0x7d085940 to=0xb2a72678, transport = 0, WantAck=0, HopLim=0 Ch=0x8 encrypted len=29 nextHop=0x78 relay=0x40 priority=120)
[13:07:49]DEBUG | ??:??:?? 698 [Screen] TraceRoute drawFrame called: runState=2
[13:07:50]DEBUG | ??:??:?? 699 [Screen] TraceRoute drawFrame called: runState=2
[13:07:51]DEBUG | ??:??:?? 700 [Screen] TraceRoute drawFrame called: runState=2
[13:07:52]DEBUG | ??:??:?? 701 [Screen] TraceRoute drawFrame called: runState=2
[13:07:52]DEBUG | ??:??Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1). 
[13:07:52]
[13:07:52]Core  1 register dump:
[13:07:52]PC      : 0x40056f90  PS      : 0x00060734  A0      : 0x80381f62  A1      : 0x3fc9cec0  
[13:07:52]A2      : 0x3fcf795c  A3      : 0x3fc9cf30  A4      : 0x00000004  A5      : 0x3fcf795c  
[13:07:52]A6      : 0x3fcf7c90  A7      : 0x00000000  A8      : 0x00000000  A9      : 0x00000004  
[13:07:52]A10     : 0x00060023  A11     : 0x80000001  A12     : 0x403758c5  A13     : 0x3fc9cfb0  
[13:07:52]A14     : 0x00000000  A15     : 0x3fc9bc00  SAR     : 0x00000019  EXCCAUSE: 0x00000006  
[13:07:52]EXCVADDR: 0x00000000  LBEG    : 0x40056f5c  LEND    : 0x40056f72  LCOUNT  : 0xffffffff  
[13:07:52]Core  1 was running in ISR context:
[13:07:52]EPC1    : 0x4217fe0b  EPC2    : 0x00000000  EPC3    : 0x00000000  EPC4    : 0x40056f90
[13:07:52]
[13:07:52]
[13:07:52]Backtrace: 0x40056f8d:0x3fc9cec0 0x40381f5f:0x3fc9ced0 0x403825f9:0x3fc9cef0 0x4208de9b:0x3fc9cf20 0x42017fa1:0x3fc9cf50 0x40375861:0x3fc9cf70 0x40375886:0x3fc9cf90 0x40379f61:0x3fc9cfb0 0x403758c2:0x3fcf5dc0 0x420bae39:0x3fcf5de0 0x40382f18:0x3fcf5e00
[13:07:52]
[13:07:52]
[13:07:52]Core  0 register dump:
[13:07:52]PC      : 0x40056964  PS      : 0x00060f34  A0      : 0x82018911  A1      : 0x3fcbbe20  
[13:07:52]A2      : 0x00000000  A3      : 0x00000000  A4      : 0x00000000  A5      : 0x00000000  
[13:07:52]A6      : 0x3fcf7c90  A7      : 0x00000000  A8      : 0x0000fa00  A9      : 0x0000000a  
[13:07:52]A10     : 0xfa000000  A11     : 0xb0c8bd40  A12     : 0xbd400000  A13     : 0xb0c80000  
[13:07:52]A14     : 0x3fcb3c6c  A15     : 0x3fcb3c6c  SAR     : 0x0000000a  EXCCAUSE: 0x00000006  
[13:07:52]EXCVADDR: 0x00000000  LBEG    : 0x40056f5c  LEND    : 0x40056f72  LCOUNT  : 0xffffffff  
[13:07:52]
[13:07:52]
[13:07:52]Backtrace: 0x40056961:0x3fcbbe20 0x4201890e:0x3fcbbe40 0x4208df2f:0x3fcbbe60 0x4208e039:0x3fcbbe90
[13:07:52]
[13:07:52]
[13:07:52]
[13:07:52]
[13:07:52]ELF file SHA256: 3b1549c9d661c12f
[13:07:52]
[13:07:52]Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1). 
[13:07:52]
[13:07:52]Core  1 register dump:
[13:07:52]PC      : 0x4038a45b  PS      : 0x00020a34  A0      : 0x820fc3d6  A1      : 0x3fc9ccd0  
[13:07:52]A2      : 0x00020a23  A3      : 0xa5a5a5a5  A4      : 0x820fc3d6  A5      : 0x00060a25  
[13:07:52]A6      : 0xfffbfff0  A7      : 0x00000046  A8      : 0x3fca068c  A9      : 0x00000001  
[13:07:52]A10     : 0x60000000  A11     : 0x00000001  A12     : 0x0000000a  A13     : 0x3fc9ccbc  
[13:07:52]A14     : 0x00000001  A15     : 0x3fcbbe90  SAR     : 0x0000000a  EXCCAUSE: 0x00000006  
[13:07:52]EXCVADDR: 0x00000000  LBEG    : 0x400570e8  LEND    : 0x400570f3  LCOUNT  : 0x00000000  
[13:07:52]Core  1 was running in ISR context:
[13:07:52]EPC1    : 0x4217fe0b  EPC2    : 0x00000000  EPC3    : 0x00000000  EPC4    : 0x4038a45b
[13:07:52]
[13:07:52]
[13:07:53]Backtrace: 0x4038a458:0x3fc9ccd0 0x420fc3d3:0x3fc9cce0 0x420fc9d9:0x3fc9cd00 0x420bbcce:0x3fc9cd20 0x420bbfce:0x3fc9cd90 0x40377f31:0x3fc9cde0 0x403778e8:0x3fc9ce00 0x00040022:0x3fc9cec0 |<-CORRUPTED
[13:07:53]
[13:07:53]
[13:07:53]Core  0 register dump:
[13:07:53]PC      : 0x40056964  PS      : 0x00060f34  A0      : 0x82018911  A1      : 0x3fcbbe20  
[13:07:53]A2      : 0x00000000  A3      : 0x00000000  A4      : 0x00000000  A5      : 0x00000000  
[13:07:53]A6      : 0x3fcf7c90  A7      : 0x00000000  A8      : 0x0000fa00  A9      : 0x0000000a  
[13:07:53]A10     : 0xfa000000  A11     : 0xb0c8bd40  A12     : 0xbd400000  A13     : 0xb0c80000  
[13:07:53]A14     : 0x3fcb3c6c  A15     : 0x3fcb3c6c  SAR     : 0x0000000a  EXCCAUSE: 0x00000006  
[13:07:53]EXCVADDR: 0x00000000  LBEG    : 0x40056f5c  LEND    : 0x40056f72  LCOUNT  : 0xffffffff  
[13:07:53]
[13:07:53]
[13:07:53]Backtrace: 0x40056961:0x3fcbbe20 0x4201890e:0x3fcbbe40 0x4208df2f:0x3fcbbe60 0x4208e039:0x3fcbbe90
[13:07:53]
[13:07:53]
[13:07:53]
[13:07:53]
[13:07:53]ELF file SHA256: 3b1549c9d661c12f
[13:07:53]
[13:07:53]Re-entered core dump! Exception happened during core dump!
[13:07:53]Rebooting...
[13:07:53]ESP-ROM:esp32s3-20210327
[13:07:53]Build:Mar 27 2021
[13:07:53]rst:0xc (RTC_SW_CPU_RST),boot:0x2b (SPI_FAST_FLASH_BOOT)
[13:07:53]Saved PC:0x420bbeda
[13:07:53]SPIWP:0xee
[13:07:53]mode:DIO, clock div:1
[13:07:53]load:0x3fce3808,len:0x4bc
[13:07:53]load:0x403c9700,len:0xbd8
[13:07:53]load:0x403cc700,len:0x2a0c
[13:07:53]entry 0x403c98d0
[13:07:54][  1296][I][esp32-hal-psram.c:96] psramInit(): PSRAM enabled
[13:07:54][  1313][I][esp32-hal-i2c.c:75] i2cInit(): Initialising I2C Master: sda=3 scl=2 freq=100000
[13:07:54]ï¿½ï¿½�@INFO  | ??:??:?? 1 
[13:07:54]
[13:07:54]//\ E S H T /\ S T / C
[13:07:54]
[13:07:54]INFO  | ??:??:?? 1 Booted, wake cause 0 (boot count 1), reset_reason=reset
[13:07:54]DEBUG | ??:??:?? 1 Filesystem files (28672/3538944 Bytes):
[13:07:54]DEBUG | ??:??:?? 1  /prefs/channels.proto (57 Bytes)
[13:07:54]DEBUG | ??:??:?? 1  /prefs/config.proto (290 Bytes)
[13:07:54]DEBUG | ??:??:?? 1  /prefs/device.proto (128 Bytes)
[13:07:54]DEBUG | ??:??:?? 1  /prefs/module.proto (120 Bytes)
[13:07:54]DEBUG | ??:??:?? 1  /prefs/nodes.proto (1819 Bytes)
[13:07:54]DEBUG | ??:??:?? 1  /static/.gitkeep (0 Bytes)
[13:07:54][  1437][W][Wire.cpp:301] begin(): Bus already started in Master Mode.
[13:07:54]DEBUG | ??:??:?? 1 Power::lipoInit lipo sensor is not ready yet
[13:07:54][  1445][I][XPowersCommon.tpp:454] begin(): SDA:3 SCL:2
[13:07:54][  1450][W][Wire.cpp:301] begin(): Bus already started in Master Mode.
[13:07:54]INFO  | ??:??:?? 1 PPM BQ25896 init succeeded
[13:07:54](230) Checking chosen profile
[13:07:54]DEBUG | ??:??:?? 1 BQ27220 fullCharge capacity: 1500
[13:07:54]DEBUG | ??:??:?? 1 BQ27220 remaining capacity: 1500
[13:07:54]DEBUG | ??:??:?? 1 Power::lipoChargerInit lipo sensor is ready
[13:07:54]INFO  | ??:??:?? 1 Scan for i2c devices
[13:07:54]DEBUG | ??:??:?? 1 Scan for I2C devices on port 1
[13:07:54]DEBUG | ??:??:?? 1 Register value: 0xff
[13:07:54]DEBUG | ??:??:?? 1 Register value: 0xff
[13:07:54]DEBUG | ??:??:?? 1 Register value: 0xfd
[13:07:54]INFO  | ??:??:?? 1 TCA9535 found at address 0x20
[13:07:54]INFO  | ??:??:?? 1 BHI260AP found at address 0x28
[13:07:54]DEBUG | ??:??:?? 1 Register value: 0x0
[13:07:54]INFO  | ??:??:?? 1 TCA8418 found at address 0x34
[13:07:54]INFO  | ??:??:?? 1 PCF8563 found at address 0x51
[13:07:54]DEBUG | ??:??:?? 1 Register value: 0xff
[13:07:54]INFO  | ??:??:?? 1 BQ27220 found at address 0x55
[13:07:54]DEBUG | ??:??:?? 1 Register value: 0x0
[13:07:54]DEBUG | ??:??:?? 1 Register value: 0xe0
[13:07:54]INFO  | ??:??:?? 1 DRV2605 found at address 0x5a
[13:07:54]DEBUG | ??:??:?? 1 Register value: 0x73
[13:07:54]DEBUG | ??:??:?? 1 Register value: 0x6
[13:07:54]INFO  | ??:??:?? 1 BQ25896 found at address 0x6b
[13:07:54]INFO  | ??:??:?? 1 7 I2C devices found
[13:07:54]DEBUG | ??:??:?? 1 acc_info = 0
[13:07:54][  1832][W][sd_diskio.cpp:174] sdCommand(): no token received
[13:07:55][  1938][W][sd_diskio.cpp:174] sdCommand(): no token received
[13:07:55][  2044][W][sd_diskio.cpp:174] sdCommand(): no token received
[13:07:55][  2150][E][sd_diskio.cpp:199] sdCommand(): Card Failed! cmd: 0x00
[13:07:55][  2156][W][sd_diskio.cpp:516] ff_sd_initialize(): GO_IDLE_STATE failed
[13:07:55][  2162][E][sd_diskio.cpp:806] sdcard_mount(): f_mount failed: (3) The physical drive cannot work
[13:07:55][  2671][W][sd_diskio.cpp:104] sdWait(): Wait Failed
[13:07:55][  2675][E][sd_diskio.cpp:126] sdSelectCard(): Select Failed
[13:07:55]DEBUG | ??:??:?? 2 No SD_MMC card detected
[13:07:55]INFO  | ??:??:?? 2 S:B:103,2.7.13.0a124b7f3,tlora-pager-ru,vardas/meshtastic_firmware_mirror
[13:07:55]INFO  | ??:??:?? 2 Build timestamp: 1762203600
[13:07:55]DEBUG | ??:??:?? 2 Total heap: 250776
[13:07:55]DEBUG | ??:??:?? 2 Free heap: 211320
[13:07:55]DEBUG | ??:??:?? 2 Total PSRAM: 8386295
[13:07:55]DEBUG | ??:??:?? 2 Free PSRAM: 8386295
[13:07:55]DEBUG | ??:??:?? 2 NVS: UsedEntries 79, FreeEntries 551, AllEntries 630, NameSpaces 5
[13:07:55]DEBUG | ??:??:?? 2 Setup Preferences in Flash Storage
[13:07:55]DEBUG | ??:??:?? 2 Number of Device Reboots: 13
[13:07:55]INFO  | ??:??:?? 2 BLE OTA firmware version 0.3.0.c535519
[13:07:55]INFO  | ??:??:?? 2 No WiFi OTA firmware available
[13:07:55]INFO  | ??:??:?? 2 Init NodeDB
[13:07:55][  2702][E][vfs_api.cpp:105] open(): /littlefs/static/static does not exist, no permits for creation
[13:07:55][  2714][E][vfs_api.cpp:105] open(): /littlefs/prefs/db.proto does not exist, no permits for creation
[13:07:55]INFO  | ??:??:?? 2 Load /prefs/nodes.proto
[13:07:55]INFO  | ??:??:?? 2 Loaded /prefs/nodes.proto successfully
[13:07:55]INFO  | ??:??:?? 2 Loaded saved nodedatabase version 24, with nodes count: 17
[13:07:55]INFO  | ??:??:?? 2 Load /prefs/device.proto
[13:07:55]INFO  | ??:??:?? 2 Loaded /prefs/device.proto successfully
[13:07:55]INFO  | ??:??:?? 2 Loaded saved devicestate version 24
[13:07:55]INFO  | ??:??:?? 2 Load /prefs/config.proto
[13:07:55]INFO  | ??:??:?? 2 Loaded /prefs/config.proto successfully
[13:07:55]INFO  | ??:??:?? 2 Loaded saved config version 24
[13:07:55]INFO  | ??:??:?? 2 Load /prefs/module.proto
[13:07:55]INFO  | ??:??:?? 2 Loaded /prefs/module.proto successfully
[13:07:55]INFO  | ??:??:?? 2 Loaded saved moduleConfig version 24
[13:07:55]INFO  | ??:??:?? 2 Load /prefs/channels.proto
[13:07:55]INFO  | ??:??:?? 2 Loaded /prefs/channels.proto successfully
[13:07:55]INFO  | ??:??:?? 2 Loaded saved channelFile version 24
[13:07:55][  2864][E][vfs_api.cpp:105] open(): /littlefs/prefs/uiconfig.proto does not exist, no permits for creation
[13:07:55]ERROR | ??:??:?? 2 Could not open / read /prefs/uiconfig.proto
[13:07:55]DEBUG | ??:??:?? 2 cleanupMeshDB purged 2 entries
[13:07:55]DEBUG | ??:??:?? 2 Use nodenum 0x7d085940 
[13:07:55]DEBUG | ??:??:?? 2 Number of Device Reboots: 13
[13:07:56]DEBUG | ??:??:?? 2 Expand short PSK #1
[13:07:56]INFO  | ??:??:?? 2 Wanted region 9, using RU
[13:07:56]DEBUG | ??:??:?? 2 Coerce telemetry to min of 30 minutes on defaults
[13:07:56]INFO  | ??:??:?? 2 Sort took 0 milliseconds
[13:07:56]DEBUG | ??:??:?? 2 Save to disk 4
[13:07:56]DEBUG | ??:??:?? 2 Opening /prefs/device.proto, fullAtomic=1
[13:07:56]INFO  | ??:??:?? 2 Save /prefs/device.proto
[13:07:56]WARN  | ??:??:?? 3 Packet History - Invalid size -1, using default 500
[13:07:56][  3027][W][Wire.cpp:301] begin(): Bus already started in Master Mode.
[13:07:56]DEBUG | ??:??:?? 3 SPI.begin(SCK=35, MISO=33, MOSI=34, NSS=36)
[13:07:56]INFO  | ??:??:?? 3 Protobuf Value uiconfig.screen_rgb_color: 0
[13:07:56]DEBUG | ??:??:?? 3 TFTDisplay!
[13:07:56]DEBUG | ??:??:?? 3 Use compiled/slipstreamed tzplaceholder                                         
[13:07:56]DEBUG | ??:??:?? 3 Saved TZ: MSK-3 
[13:07:56]DEBUG | ??:??:?? 3 Set Timezone to MSK-3
[13:07:56]INFO  | ??:??:?? 3 GPS power state move from OFF to ACTIVE
[13:07:56]DEBUG | ??:??:?? 3 Use GPIO4 for GPS RX
[13:07:56]DEBUG | ??:??:?? 3 Use GPIO12 for GPS TX
[13:07:56]DEBUG | ??:??:?? 3 Start audio thread
[13:07:56]DEBUG | ??:??:?? 3 Start multicast thread
[13:07:56]INFO  | ??:??:?? 3 RotaryEncoder initialized pins(40, 41, 7), events(28, 29, 10)
[13:07:56]DEBUG | ??:??:?? 3 TCA8418 Reset
[13:07:56][  3062][E][vfs_api.cpp:105] open(): /littlefs/prefs/cannedConf.proto does not exist, no permits for creation
[13:07:56]ERROR | ??:??:?? 3 Could not open / read /prefs/cannedConf.proto
[13:07:56]INFO  | ??:??:?? 3 CannedMessageModule is enabled
[13:07:56][  3078][E][vfs_api.cpp:105] open(): /littlefs/prefs/ringtone.proto does not exist, no permits for creation
[13:07:56]ERROR | ??:??:?? 3 Could not open / read /prefs/ringtone.proto
[13:07:56]INFO  | ??:??:?? 3 Init External Notification Module
[13:07:56]INFO  | ??:??:?? 3 Do TFT init
[13:07:56]INFO  | ??:??:?? 3 Power to TFT Backlight
[13:07:56]INFO  | ??:??:?? 3 Applied screen brightness: 153
[13:07:56]INFO  | ??:??:?? 3 Turn on screen
[13:07:56]DEBUG | ??:??:?? 3 waypoint wants a UI Frame
[13:07:56]DEBUG | ??:??:?? 3 traceroute wants a UI Frame
[13:07:56]DEBUG | ??:??:?? 3 canned wants a UI Frame
[13:07:56]DEBUG | ??:??:?? 3 Audio wants a UI Frame
[13:07:56]DEBUG | ??:??:?? 3 SX126xInterface(cs=36, irq=14, rst=47, busy=48)
[13:07:56]DEBUG | ??:??:?? 3 SX126X_DIO3_TCXO_VOLTAGE defined, using DIO3 as TCXO reference voltage at 3.000000 V
[13:07:56]INFO  | ??:??:?? 3 Start meshradio init
[13:07:56]INFO  | ??:??:?? 3 Radio freq=869.075, config.lora.frequency_offset=0.000
[13:07:56]INFO  | ??:??:?? 3 Set radio: region=RU, name=LongFast, config=0, ch=1, power=20
[13:07:56]INFO  | ??:??:?? 3 myRegion->freqStart -> myRegion->freqEnd: 868.700012 -> 869.200012 (0.500000 MHz)
[13:07:56]INFO  | ??:??:?? 3 numChannels: 2 x 250.000kHz
[13:07:56]INFO  | ??:??:?? 3 channel_num: 2
[13:07:56]INFO  | ??:??:?? 3 frequency: 869.075012
[13:07:56]INFO  | ??:??:?? 3 Slot time: 28 msec, preamble time: 131 msec
[13:07:56]INFO  | ??:??:?? 3 Final Tx power: 20 dBm
[13:07:56]INFO  | ??:??:?? 3 SX126x init result 0
[13:07:56]INFO  | ??:??:?? 3 Frequency set to 869.075012
[13:07:56]INFO  | ??:??:?? 3 Bandwidth set to 250.000000
[13:07:56]INFO  | ??:??:?? 3 Power output set to 20
[13:07:56]DEBUG | ??:??:?? 3 Current limit set to 140.000000
[13:07:56]DEBUG | ??:??:?? 3 Current limit set result 0
[13:07:56]DEBUG | ??:??:?? 3 Set DIO2 as RF switch, result: 0
[13:07:56]DEBUG | ??:??:?? 3 SX126X_RXEN not defined, defaulting to RADIOLIB_NC
[13:07:56]DEBUG | ??:??:?? 3 SX126X_TXEN not defined, defaulting to RADIOLIB_NC
[13:07:56]DEBUG | ??:??:?? 3 Use MCU pin -1 as RXEN and pin -1 as TXEN to control RF switching
[13:07:56]INFO  | ??:??:?? 3 Set RX gain to boosted mode; result: 0
[13:07:56]INFO  | ??:??:?? 3 SX1262 init success
[13:07:56]INFO  | ??:??:?? 3 Not using WIFI
[13:07:56]DEBUG | ??:??:?? 3 LoRA bitrate = 116.967873 bytes / sec
[13:07:56]INFO  | ??:??:?? 3 PowerFSM init, USB power=1
[13:07:56]DEBUG | ??:??:?? 3 State: BOOT
[13:07:56][  3763][D][esp32-hal-cpu.c:244] setCpuFrequencyMhz(): PLL: 480 / 6 = 80 Mhz, APB: 80000000 Hz
[13:07:56]DEBUG | ??:??:?? 3 Free heap  :  178340 bytes
[13:07:56]DEBUG | ??:??:?? 3 Free PSRAM : 8299439 bytes
[13:07:56]DEBUG | ??:??:?? 3 Node status update: 15 online, 15 total
[13:07:56]DEBUG | ??:??:?? 3 [Power] BQ27220 time to full charge: 0 min
[13:07:56]DEBUG | ??:??:?? 3 [GPS] Set GPS Baud to 38400
[13:07:57]DEBUG | ??:??:?? 3 [cardKB] Use I2C Bus 0 (the first one)
```

### PR DESCRIPTION
**Pull request by thebentern**
Fixes #8565
Cached traceroute result text so we only wrap and measure strings once, reducing the per-frame work in drawFrame() that was hammering the ESP32 watchdog.

### CODE REVIEW

File: src/modules/TraceRouteModule.cpp [hunk 1]
```diff
@@ -11,6 +11,113 @@ extern graphics::Screen *screen;
...
+        String remaining = segment;
+
+        while (remaining.length() > 0) {
+            String tempLine = "";
+            int lastGoodBreak = -1;
+            bool lineComplete = false;
+
+            for (int i = 0; i < static_cast<int>(remaining.length()); i++) {
+                char ch = remaining.charAt(i);
+                String testLine = tempLine + ch;
```
Comment (mverch67) [inline src/modules/TraceRouteModule.cpp]: This string construction inside these two loops cost a lot performance (memory allocation!) and may fragment the free heap. I would rather look to use std::vector or std::array with fixed size instead.

**Review by fifieldt — APPROVED** [review]
