### PR TITLE
Clear out user.id except for sending to phone

### LINKED ISSUE #8170: [Bug]: Firmware allows the user-id to be set to an arbitrary string
### Category

Other

### Hardware

Not Applicable

### Is this bug report about any UI component firmware like InkHUD or Meshtatic UI (MUI)?

- [ ] Meshtastic UI aka MUI colorTFT
- [ ] InkHUD ePaper
- [ ] OLED slide UI on any display

### Firmware Version

2.7.3

### Description

The firmware allows the user-id to be set via protobufs to any arbitrary string.

The convention is that the user-id is set to the hex value of the node-id.

Should we check if the user-id is a valid hex string?

### Relevant log output

```Shell
How it can be set in current firmware:

id: "!kronos"
long_name: "kronos"
short_name: "BB07"

How it is conventionally set:

Import Time
10:31:48 AM - 09-30-2025
packet
from: 1128103100
to: 4294967295
channel: 24
decoded {
  portnum: NODEINFO_APP
  bitfield: 0
}
id: 3323496629
rx_time: 1759253508
rx_snr: -16.25
hop_limit: 5
rx_rssi: -107
hop_start: 7
relay_node: 12
transport_mechanism: TRANSPORT_LORA
payload
id: "!433d7cbc"
long_name: "kronos"
short_name: "BB07"
macaddr: "H\312C=|\274"
hw_model: HELTEC_WIRELESS_TRACKER
public_key: "\333\030z\300x|\037\222\351P \210N\317\372:\270\302\346\236\225\266\335\314y\242\271\007\002\251\317\006"
is_unmessagable: false
```

### PR DESCRIPTION
**Pull request by thebentern**
Closes #8170 

Avoid storing user.id as anything but a null terminated empty string and send to client as a generated value

### CODE REVIEW

File: src/mesh/NodeDB.cpp [hunk 1]
```diff
@@ -56,10 +56,6 @@
 #include <WiFiOTA.h>
 #endif
 
-// stringify
-#define xstr(s) str(s)
-#define str(s) #s
-
```
Comment (jp-bennett) [inline src/mesh/NodeDB.cpp:62]: Did this get moved somewhere? This is needed to use the build epoch as a filename.

Comment (jp-bennett) [reply src/mesh/NodeDB.cpp:62]: Ah, it's already in configuration.h.

**Comment by h3lix1** [comment]
#8228 found with this..
